// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBSKqCkaqeuXWTcW3TxMiZNEMCkn89kQs',
    appId: '1:510286580905:web:8dad701ebd445a878aadb8',
    messagingSenderId: '510286580905',
    projectId: 'foody-card-24',
    authDomain: 'foody-card-24.firebaseapp.com',
    storageBucket: 'foody-card-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDsNVd6wtazt4_86YuBVWEwgF3TnJQDk4',
    appId: '1:510286580905:android:0c078a07272c0b988aadb8',
    messagingSenderId: '510286580905',
    projectId: 'foody-card-24',
    storageBucket: 'foody-card-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK33ZuG-YOyrPlEs2FhYqf2GfBwcaFwzY',
    appId: '1:510286580905:ios:a62190b55b3a32808aadb8',
    messagingSenderId: '510286580905',
    projectId: 'foody-card-24',
    storageBucket: 'foody-card-24.appspot.com',
    iosBundleId: 'com.foodcard.foodcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK33ZuG-YOyrPlEs2FhYqf2GfBwcaFwzY',
    appId: '1:510286580905:ios:ed88f56eb11e42178aadb8',
    messagingSenderId: '510286580905',
    projectId: 'foody-card-24',
    storageBucket: 'foody-card-24.appspot.com',
    iosBundleId: 'com.foodcard.foodcard.RunnerTests',
  );
}
